---
title: "Calibración de sensores de bajo costo"
format: pdf
author: "Lenna Pedroso"
editor: visual
---

## Marco teorico

La exposición al material particulado fino PM2,5 constituye un grave riesgo para la salud, ya que estas partículas pueden penetrar profundamente en el sistema respiratorio y acumularse en el organismo, incrementando la probabilidad de enfermedades respiratorias, cáncer de pulmón y mortalidad prematura. En la Región Metropolitana de Santiago, las concentraciones de PM2,5 superan con frecuencia los límites permitidos, situación que se ve agravada por su ubicación geográfica y condiciones meteorológicas que restringen la dispersión de contaminantes, especialmente durante el invierno.

El monitoreo de la calidad del aire en la ciudad se realiza principalmente a través del sistema SINCA, el cual dispone de un número limitado de estaciones de alta precisión, lo que reduce la cobertura espacio-temporal y dificulta una representación precisa de la exposición real de la población. Asimismo, estas estaciones presentan elevados costos de instalación, mantenimiento y operación, limitando su expansión y accesibilidad, particularmente en contextos con recursos restringidos.

Los sensores de bajo costo surgen como una alternativa complementaria al permitir una mayor cobertura espacial y una mejor caracterización de la variabilidad local del PM2,5. No obstante, su desempeño se ve influenciado por factores ambientales y tienden a sobreestimar las concentraciones, por lo que requieren procesos de calibración rigurosos. En este marco, el objetivo de la investigación es calibrar sensores Plantower en la comuna de Las Condes, buscando reducir el error de medición a valores inferiores a 20 μg/m³. \## Metodología \### Gráfico de timevariation

Para verificar el comportamiento de los sensores y compararlos con los monitores de referencia, se realiza un gráfico de time variation.

```{r}
#Cargar datos
Condes_Plantawer_SINCA <- read.csv2("data/Condes_Plantawer_SINCA.csv", header = TRUE)

```
